name: "Run tests"
description: "Install fish and Oh My Fish! if necessary and run CI tests"
runs:
  using: "composite"
  steps:
    - name: Install Fish
      shell: bash
      if: runner.os == 'macOS'
      run: brew update && brew install fish

    - name: Run tests
      shell: bash
      run: tests/run.fish
